version: "3"

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - 8000:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

  postgres:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: transactions
      POSTGRES_PASSWORD: transactions
      POSTGRES_DB: transactions_db
    expose:
      - 5432

  app:
    build: ./
    container_name: app
    depends_on:
      - nginx
      - postgres
    expose:
      - 8000
    volumes:
      - ./:/transaction_app
    command: python manage.py runserver 0.0.0.0:8000
